import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsible: true,
      items: [
        'About/Welcome',
      ],
    },
    {
      type: 'category',
      label: 'Services',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Support Services',
          collapsed: true,
          items: [
            'Services/Support/Bioinformatics',
            'Services/Support/Statistics',
            'Services/Support/Proposal',
          ],
        },
        {
          type: 'category',
          label: 'Compute Services',
          items: [
            'Services/Compute/Dedicated',
            'Services/Compute/Interactive',
          ],
        },
        {
          type: 'category',
          label: 'Data Management Services',
          items: [
            'Services/Data/Storage',
            'Services/Data/Transfer',
          ],
        },
        {
          type: 'category',
          label: 'Specialized Services',
          items: [
            'Services/Specialized/Database',
            'Services/Specialized/Portals',
            'Services/Specialized/Software',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Research',
      items: [
            'Research/Areas',
            'Research/Publications',
            'Research/Collaborations',
            'Research/Innovation',
      ],
    },
  ],
};

export default sidebars;
