# Workflow name
name: Continuous Deployment

# This allows manual start of the pipeline as needed.
on:
    push:
      branches:
      - main

# The list of jobs to run 
jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:

      # 1. Configure AWS credentials      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          
      # 2. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Setup Node 
        uses: actions/setup-node@v3
        with:
          node-version: '22.5.1'


      - name: Build Website
        run: |
          npm install
          npm run build
          
      - name: Copy to S3 Bucket
        run: |
          aws s3 rm ${{ secrets.AWS_S3_BUCKET }}/ --recursive
          aws s3 cp ./dist  ${{ secrets.AWS_S3_BUCKET }} --recursive
          